### ISSUE TITLE
start-stop-daemon: user '--user' not found

### ISSUE THREAD

**Issue by PedroC1999** [sillyfrog/OctoPrint-Klipper-mjpg-Dockerfile#2]
Hello,

Trying to get this installed on the latest Ubuntu Server, the install process completes, however at the end, Klipper fails to start.

`###### Installing system start script...

###### Launching Klipper host software...
Restarting klipper: klipperStopping klipper: klipper.
Starting klipper: klipperstart-stop-daemon: user '--user' not found
 failed!
Removing intermediate container 73659f7e623e
 ---> 43cafc55e969
Step 31/35 : RUN cp klipper/config/printer-anet-a8-2017.cfg /home/octoprint/printer.cfg
 ---> Running in b574769729ef
Removing intermediate container b574769729ef
 ---> bb6169164cc3
Step 32/35 : USER root
 ---> Running in 24eb135d997a
Removing intermediate container 24eb135d997a
 ---> f24edf0a422b
Step 33/35 : COPY start.py /
 ---> becaee51aae6
Step 34/35 : COPY runklipper.py /
 ---> a0bcc8582c3e
Step 35/35 : CMD ["/start.py"]
 ---> Running in df9c05e785c5
Removing intermediate container df9c05e785c5
 ---> 9e68230233b4
Successfully built 9e68230233b4
Successfully tagged okmd:latest`

As shown above, and as mentioned in this thread before (https://github.com/KevinOConnor/klipper/pull/488) it appears to be an issue in the init.d script for launching Klipper.

I'm available to test for you if required, many thanks

**Comment by sillyfrog** [comment]
FYI: Looking at this, I'll have a push to this repo in a bit - it's involving a number of updates - and I'm also moving to an Ubuntu container so we can move to python 3 at some point in the future.

**Comment by PedroC1999** [comment]
For now I have just installed it normally, goodluck with the migration to Python3!

**Comment by sillyfrog** [comment]
FYI: This is now fixed in https://github.com/sillyfrog/OctoPrint-Klipper-mjpg-Dockerfile/commit/866f739aa80e07120002c7e1f229ad97fce29d31
