### ISSUE TITLE
Fix for error in building image

### ISSUE THREAD

**Issue by seanauff** [sillyfrog/OctoPrint-Klipper-mjpg-Dockerfile#4]
No PR because I already forked your repo awhile ago, but I was running into build issues on mine, and got the same when trying to build yours (exiting with error when installing MarkupSafe in the the octoprint install script) for the past month and finally tracked down the problem. The official OctoPrint install from source guide has a different command to install that your Dockerfile. Here is what it should look like:

```
#Install Octoprint
RUN git clone --branch $tag https://github.com/foosel/OctoPrint.git /opt/octoprint \
  && virtualenv venv \
  && ./venv/bin/pip install .
```
I was able to build images on both amd64 and arm using that change.

**Comment by sillyfrog** [comment]
Thanks!

That's a rather weird error to happen in docker on amd64 vs arm, I can't even think what maybe happening there   ¯\_(ツ)_/¯

The joy of software :) 

All tested and committed, thanks for the info!

**Comment by seanauff** [comment]
Great! I actually was getting the error on arm as well, but no matter, it is fixed now!
